# Generated by Django 5.0.1 on 2024-02-23 11:50

import django.contrib.auth.models
import myauth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0002_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=myauth.models.user_avatar_dir_path, verbose_name=django.contrib.auth.models.User),
        ),
    ]
