# Generated by Django 4.0 on 2024-02-15 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('shopapp', '0006_order_products'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['price', 'name']},
        ),
        migrations.AddField(
            model_name='product',
            name='created_by',
            field=models.OneToOneField(null=1, on_delete=django.db.models.deletion.PROTECT, to='auth.user'),
            preserve_default=1,
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_address',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(related_name='orders', to='shopapp.Product'),
        ),
    ]
